### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by pasbi** [sethmlarson/trytravis#27]
I installed _trytravis_:
```
$ sudo pip3 install trytravis
$ cd trytravis
$ trytravis --repo ssh://git@github.com/pasbi/trytravis
```

Then running `$ trytravis` fails with the following message:

```
Adding a temporary remote to `ssh://git@github.com/pasbi/trytravis`...
Adding all local changes...
Committing local changes...
Pushing to `trytravis` remote...
Waiting for a Travis build to appear for `0b7cf6b03563e800354a4f230fe482eb84e2d2cf` after `2019-01-17 23:13:54`...
Traceback (most recent call last):
  File "/usr/bin/trytravis", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/trytravis.py", line 388, in main
    _main(argv)
  File "/usr/lib/python3.7/site-packages/trytravis.py", line 378, in _main
    build_id = _wait_for_travis_build(url, commit, committed)
  File "/usr/lib/python3.7/site-packages/trytravis.py", line 211, in _wait_for_travis_build
    key=lambda x: x['committed_at']):
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by sethmlarson** [comment]
I'm not sure what caused this. I'm no longer planning on maintaining this tool.
